# Generated by Django 4.2.1 on 2023-06-25 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('normative_doc', models.CharField(max_length=255)),
                ('is_moderated', models.BooleanField(default=False)),
                ('nominal_voltage_high', models.FloatField()),
                ('nominal_voltage_low', models.FloatField()),
                ('nominal_power', models.FloatField()),
                ('short_circuit_voltage', models.FloatField()),
                ('short_circuit_active_losses', models.FloatField()),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SyncMotor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('normative_doc', models.CharField(max_length=255)),
                ('is_moderated', models.BooleanField(default=False)),
                ('supertrancsient_resistance_relative', models.FloatField(blank=True, null=True)),
                ('nominal_active_power', models.FloatField()),
                ('nominal_voltage', models.FloatField()),
                ('efficiency', models.FloatField()),
                ('cos_fi', models.FloatField()),
                ('damping_constant', models.FloatField()),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('normative_doc', models.CharField(max_length=255)),
                ('is_moderated', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Cable', 'CABLE'), ('Wire', 'WIRE')], default='Wire', max_length=16)),
                ('active_resistivity', models.FloatField()),
                ('reactive_resistivity', models.FloatField()),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutoTransformer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('normative_doc', models.CharField(max_length=255)),
                ('is_moderated', models.BooleanField(default=False)),
                ('nominal_voltage_high', models.FloatField()),
                ('nominal_voltage_mid', models.FloatField()),
                ('nominal_voltage_low', models.FloatField()),
                ('nominal_power', models.FloatField()),
                ('short_circuit_voltage_high_mid', models.FloatField()),
                ('short_circuit_voltage_high_low', models.FloatField()),
                ('short_circuit_voltage_mid_low', models.FloatField()),
                ('short_circuit_active_losses_high_mid', models.FloatField()),
                ('short_circuit_active_losses_high_low', models.FloatField()),
                ('short_circuit_active_losses_mid_low', models.FloatField()),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AsyncMotor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('normative_doc', models.CharField(max_length=255)),
                ('is_moderated', models.BooleanField(default=False)),
                ('supertrancsient_resistance_relative', models.FloatField(blank=True, null=True)),
                ('nominal_active_power', models.FloatField()),
                ('nominal_voltage', models.FloatField()),
                ('efficiency', models.FloatField()),
                ('cos_fi', models.FloatField()),
                ('damping_constant', models.FloatField()),
                ('starting_current_factor', models.FloatField(blank=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
