# Generated by Django 4.2.1 on 2023-07-06 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apparatus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('normative_doc', models.CharField(max_length=255)),
                ('is_moderated', models.BooleanField(default=False)),
                ('supertrancsient_resistance_relative', models.FloatField(blank=True, null=True)),
                ('nominal_active_power', models.FloatField()),
                ('nominal_voltage', models.FloatField()),
                ('efficiency', models.FloatField()),
                ('cos_fi', models.FloatField()),
                ('damping_constant', models.FloatField()),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
