version: "3.1"

services:
  backend:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 electro.asgi:application
    volumes:
      - .:/electro
    expose:
      - 8000
    restart: always
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:15.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    env_file:
      - .env
    restart: unless-stopped
  memcached:
    image: memcached:latest
    restart:
      always
    expose:
      - 11211
  redis:
    image: redis:latest
    restart: always
  celery:
    build: .
    command: celery -A electro worker -l info
    restart: always
    volumes:
      - .:/electro
    depends_on:
      - redis
  celery_beat:
    build: .
    command: celery -A electro beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    restart: always
    volumes:
      - .:/electro
    depends_on:
      - redis
      - celery
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx/:/electro/logs/nginx/
      - ./static_files/:/electro/static_files/
      - ./media/:/electro/media/
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data: